In [1]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Importing the dataset
X_train=pd.read_table('X_train.txt',delim_whitespace=True,header=None)
X_test=pd.read_table('X_test.txt',delim_whitespace=True,header=None)
y_train=pd.read_table('y_train.txt',delim_whitespace=True,header=None)
y_test=pd.read_table('y_test.txt',delim_whitespace=True,header=None)

In [3]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [4]:
#Task-B
#Fitting K-Nearest Neighbors classifier to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(X_train,y_train)

/srv/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [5]:
#Predicting the test set results
y_pred=classifier.predict(X_test)

In [7]:
#Making the confusion matrix,classification report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print('\n')
cr=classification_report(y_test,y_pred)
print(cr)

[[483   4   9   0   0   0]
 [ 43 425   3   0   0   0]
 [ 61  54 305   0   0   0]
 [  0   2   0 373 114   2]
 [  0   0   0  35 497   0]
 [  0   0   0  15  11 511]]


             precision    recall  f1-score   support

          1       0.82      0.97      0.89       496
          2       0.88      0.90      0.89       471
          3       0.96      0.73      0.83       420
          4       0.88      0.76      0.82       491
          5       0.80      0.93      0.86       532
          6       1.00      0.95      0.97       537

avg / total       0.89      0.88      0.88      2947



In [8]:
#Applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,scoring='f1_micro',X=X_train,y=y_train,cv=10)
print(accuracies.mean())
print(accuracies.std())

/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when

0.8818521072101095
0.03346480892133874


In [ ]:
#Applying Grid Search to find the best model andthe best parameters
from sklearn.model_selection import GridSearchCV
parameters=[{'n_neighbors':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50]}]
grid_search =GridSearchCV(estimator=classifier,param_grid=parameters,scoring='f1_micro',cv=10)
grid_search=grid_search.fit(X_train,y_train)
best_f1score=grid_search.best_score_
print(best_f1score)
best_parameters =grid_search.best_params_
print(best_parameters)

/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when

/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


In [ ]:
grid_predictions=grid_search.predict(X_test)
print(grid_predictions)

In [ ]:
#Making the confusion matrix,classification report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm1=confusion_matrix(y_test,grid_predictions)
print(cm1)
print('\n')
cr1=classification_report(y_test,grid_predictions)
print(cr1)

In [ ]:
error_rate=[]
for i in range(1,50):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i=knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))

plt.figure(figsize=(10,6))
plt.plot(range(1,50),error_rate,color='blue',linestyle='dashed',marker='o',markerfacecolor='red',markersize=10)
plt.title('Error Rate vs K value')
plt.xlabel('k')
plt.ylabel('Error Rate')