In [2]:
#Task D:
#Fitting Kernal SVM to the training set
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Importing the dataset
X_train=pd.read_table('X_train.txt',delim_whitespace=True,header=None)
X_test=pd.read_table('X_test.txt',delim_whitespace=True,header=None)
y_train=pd.read_table('y_train.txt',delim_whitespace=True,header=None)
y_test=pd.read_table('y_test.txt',delim_whitespace=True,header=None)

In [4]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [5]:
from sklearn.svm import SVC
classifier=SVC(kernel='rbf',random_state=0)
classifier.fit(X_train,y_train)

/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
#Predicting the test set results
y_pred=classifier.predict(X_test)

In [7]:
#Making the confusion matrix,classification report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print('\n')
cr=classification_report(y_test,y_pred)
print(cr)

[[482   6   8   0   0   0]
 [ 14 456   1   0   0   0]
 [  6  28 386   0   0   0]
 [  0   1   0 442  46   2]
 [  0   0   0  29 503   0]
 [  0   0   0   0   0 537]]


             precision    recall  f1-score   support

          1       0.96      0.97      0.97       496
          2       0.93      0.97      0.95       471
          3       0.98      0.92      0.95       420
          4       0.94      0.90      0.92       491
          5       0.92      0.95      0.93       532
          6       1.00      1.00      1.00       537

avg / total       0.95      0.95      0.95      2947



In [8]:
#Applying Grid Search to find the best model andthe best parameters
from sklearn.model_selection import GridSearchCV
parameters=[{'C':[1,10,100,1000],        
            'gamma':[1e-3,1e-4]}]
grid_search =GridSearchCV(estimator=classifier,param_grid=parameters,scoring='f1_micro',cv=10,verbose=3,n_jobs=-1)
grid_search=grid_search.fit(X_train,y_train)

Fitting 10 folds for each of 8 candidates, totalling 80 fits
[CV] C=1, gamma=0.001 ................................................
[CV] C=1, gamma=0.001 ................................................
[CV] C=1, gamma=0.001 ................................................
[CV] C=1, gamma=0.001 ................................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] C=1, gamma=0.001 ................................................
[CV] C=1, gamma=0.001 ................................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] C=1, gamma=0.001 ................................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] C=1, gamma=0.001 ................................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ....... C=1, gamma=0.001, score=0.8726287262872628, total= 1.4min
[CV] C=1, gamma=0.001 ................................................
[CV] ....... C=1, gamma=0.001, score=0.9483695652173914, total= 1.3min
[CV] C=1, gamma=0.001 ................................................
[CV] ....... C=1, gamma=0.001, score=0.8616010854816826, total= 1.3min
[CV] C=1, gamma=0.0001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .................. C=1, gamma=0.001, score=0.90625, total= 1.5min
[CV] C=1, gamma=0.0001 ...............................................
[CV] ........ C=1, gamma=0.001, score=0.975609756097561, total= 1.3min
[CV] C=1, gamma=0.0001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ........ C=1, gamma=0.001, score=0.964769647696477, total= 1.6min
[CV] C=1, gamma=0.0001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ........ C=1, gamma=0.001, score=0.956343792633015, total= 1.5min
[CV] C=1, gamma=0.0001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ....... C=1, gamma=0.001, score=0.9740437158469946, total= 1.5min
[CV] C=1, gamma=0.0001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ....... C=1, gamma=0.001, score=0.9617486338797814, total= 1.3min
[CV] C=1, gamma=0.0001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ....... C=1, gamma=0.001, score=0.9576502732240437, total= 1.5min
[CV] C=1, gamma=0.0001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=1, gamma=0.0001, score=0.8344640434192673, total= 2.3min
[CV] C=1, gamma=0.0001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=1, gamma=0.0001, score=0.8550135501355014, total= 2.6min
[CV] C=1, gamma=0.0001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ....... C=1, gamma=0.0001, score=0.926829268292683, total= 2.8min
[CV] C=10, gamma=0.001 ...............................................
[CV] ...... C=1, gamma=0.0001, score=0.9307065217391305, total= 2.6min
[CV] C=10, gamma=0.001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=1, gamma=0.0001, score=0.9525745257452576, total= 2.7min
[CV] C=10, gamma=0.001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=1, gamma=0.0001, score=0.8858695652173914, total= 2.8min
[CV] C=10, gamma=0.001 ...............................................


[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed: 10.9min
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=10, gamma=0.001, score=0.8726287262872628, total=  58.2s
[CV] C=10, gamma=0.001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=10, gamma=0.001, score=0.9769647696476965, total= 1.1min
[CV] C=10, gamma=0.001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ....... C=10, gamma=0.001, score=0.964769647696477, total= 1.1min
[CV] C=10, gamma=0.001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=1, gamma=0.0001, score=0.9290586630286494, total= 2.5min
[CV] C=10, gamma=0.001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=10, gamma=0.001, score=0.8751696065128901, total= 1.2min
[CV] C=10, gamma=0.001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=1, gamma=0.0001, score=0.9180327868852459, total= 2.6min
[CV] C=10, gamma=0.001 ...............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=10, gamma=0.001, score=0.9592391304347826, total= 1.1min
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=10, gamma=0.001, score=0.9279891304347826, total= 1.0min
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=10, gamma=0.001, score=0.9631650750341064, total= 1.0min
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=10, gamma=0.001, score=0.9863387978142076, total= 1.1min
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=10, gamma=0.001, score=0.9631147540983607, total= 1.1min
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=10, gamma=0.001, score=0.9713114754098361, total=  57.4s
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=1, gamma=0.0001, score=0.9467213114754098, total= 2.4min
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=1, gamma=0.0001, score=0.9221311475409836, total= 2.6min
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.9728997289972899, total= 1.0min
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.8780487804878049, total= 1.1min
[CV] C=10, gamma=0.0001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.9607046070460704, total= 1.1min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.8426051560379919, total= 1.0min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.9538043478260869, total= 1.1min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.9157608695652174, total= 1.1min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.9713506139154161, total= 1.1min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.9726775956284153, total= 1.1min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.9590163934426229, total= 1.0min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ....... C=100, gamma=0.001, score=0.86449864498645, total= 1.1min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=100, gamma=0.001, score=0.9823848238482384, total= 1.1min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=10, gamma=0.0001, score=0.9603825136612022, total= 1.2min
[CV] C=100, gamma=0.001 ..............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ...... C=100, gamma=0.001, score=0.964769647696477, total= 1.1min
[CV] C=100, gamma=0.0001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=100, gamma=0.001, score=0.9538043478260869, total=  56.2s
[CV] C=100, gamma=0.0001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=100, gamma=0.001, score=0.8751696065128901, total= 1.1min
[CV] C=100, gamma=0.0001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=100, gamma=0.001, score=0.9293478260869565, total= 1.2min
[CV] C=100, gamma=0.0001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=100, gamma=0.0001, score=0.9728997289972899, total=  42.0s
[CV] C=100, gamma=0.0001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=100, gamma=0.0001, score=0.8794037940379403, total=  35.9s
[CV] C=100, gamma=0.0001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=100, gamma=0.001, score=0.9863387978142076, total=  54.6s
[CV] C=100, gamma=0.0001 .............................................
[CV] ..... C=100, gamma=0.001, score=0.9590723055934516, total= 1.1min


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] C=100, gamma=0.0001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=100, gamma=0.0001, score=0.962059620596206, total=  41.4s
[CV] C=100, gamma=0.0001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=100, gamma=0.001, score=0.9685792349726776, total= 1.2min
[CV] C=100, gamma=0.0001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=100, gamma=0.001, score=0.9795081967213115, total= 1.1min
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=100, gamma=0.0001, score=0.8575305291723202, total=  50.0s
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=100, gamma=0.0001, score=0.9592391304347826, total=  45.7s
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=100, gamma=0.0001, score=0.9890710382513661, total=  39.3s
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=100, gamma=0.0001, score=0.9347826086956522, total=  44.7s
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=100, gamma=0.0001, score=0.9795361527967258, total=  42.3s
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=100, gamma=0.0001, score=0.9644808743169399, total=  48.2s
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=100, gamma=0.0001, score=0.9644808743169399, total=  40.8s
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=1000, gamma=0.001, score=0.8672086720867209, total=  53.8s
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ..... C=1000, gamma=0.001, score=0.981029810298103, total= 1.1min
[CV] C=1000, gamma=0.001 .............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=1000, gamma=0.001, score=0.8738127544097694, total= 1.1min
[CV] C=1000, gamma=0.0001 ............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=1000, gamma=0.001, score=0.9661246612466124, total= 1.1min
[CV] C=1000, gamma=0.0001 ............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=1000, gamma=0.001, score=0.9510869565217391, total= 1.1min
[CV] C=1000, gamma=0.0001 ............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=1000, gamma=0.001, score=0.9293478260869565, total= 1.0min
[CV] C=1000, gamma=0.0001 ............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=1000, gamma=0.001, score=0.9590723055934516, total= 1.1min
[CV] C=1000, gamma=0.0001 ............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=1000, gamma=0.001, score=0.9863387978142076, total= 1.0min
[CV] C=1000, gamma=0.0001 ............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=1000, gamma=0.001, score=0.9795081967213115, total= 1.1min
[CV] C=1000, gamma=0.0001 ............................................
[CV] ... C=1000, gamma=0.0001, score=0.8739837398373984, total=  36.3s
[CV] C=1000, gamma=0.0001 ............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] .... C=1000, gamma=0.001, score=0.9699453551912568, total= 1.1min
[CV] C=1000, gamma=0.0001 ............................................
[CV] .... C=1000, gamma=0.0001, score=0.975609756097561, total=  38.8s


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] C=1000, gamma=0.0001 ............................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ... C=1000, gamma=0.0001, score=0.9661246612466124, total=  41.8s
[CV] ... C=1000, gamma=0.0001, score=0.8697421981004071, total=  36.2s
[CV] ... C=1000, gamma=0.0001, score=0.9551630434782609, total=  44.8s
[CV] ... C=1000, gamma=0.0001, score=0.9456521739130435, total=  42.6s
[CV] .... C=1000, gamma=0.0001, score=0.975443383356071, total=  32.4s
[CV] ... C=1000, gamma=0.0001, score=0.9904371584699454, total=  32.7s
[CV] ... C=1000, gamma=0.0001, score=0.9713114754098361, total=  33.3s
[CV] ... C=1000, gamma=0.0001, score=0.9795081967213115, total=  34.2s


[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed: 30.4min finished
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
best_f1score=grid_search.best_score_
print(best_f1score)
best_parameters =grid_search.best_params_
print(best_parameters)

0.9502176278563657
{'C': 1000, 'gamma': 0.0001}


NameError: name 'grid_searh' is not defined

In [10]:
grid_predictions=grid_search.predict(X_test)
print(grid_predictions)

[5 5 5 ... 2 2 2]


In [11]:
#Making the confusion matrix,classification report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm1=confusion_matrix(y_test,grid_predictions)
print(cm1)
print('\n')
cr1=classification_report(y_test,grid_predictions)
print(cr1)

[[493   0   3   0   0   0]
 [ 16 453   2   0   0   0]
 [  5  17 398   0   0   0]
 [  0   2   0 435  54   0]
 [  0   0   0  15 517   0]
 [  0   0   0   0   0 537]]


             precision    recall  f1-score   support

          1       0.96      0.99      0.98       496
          2       0.96      0.96      0.96       471
          3       0.99      0.95      0.97       420
          4       0.97      0.89      0.92       491
          5       0.91      0.97      0.94       532
          6       1.00      1.00      1.00       537

avg / total       0.96      0.96      0.96      2947



In [12]:
#Applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,scoring='f1_micro',X=X_train,y=y_train,cv=10,verbose=3,n_jobs=-1)
print(accuracies.mean())
print(accuracies.std())

[CV]  ................................................................
[CV]  ................................................................
[CV]  ................................................................
[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV]  ................................................................
[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[CV] ....................... , score=0.8683853459972863, total= 1.6min
[CV]  ................................................................
[CV] ......................... , score=0.86449864498645, total= 1.6min
[CV]  ................................................................
[CV] ....................... , score=0.9551630434782609, total= 1.6min
[CV] ....................... , score=0.9413369713506139, total= 1.6min


[Parallel(n_jobs=-1)]: Done   3 out of  10 | elapsed:  1.6min remaining:  3.8min


[CV] ........................ , score=0.904891304347826, total= 1.6min
[CV] ........................ , score=0.959349593495935, total= 1.7min
[CV] ....................... , score=0.9769647696476965, total= 1.7min


[Parallel(n_jobs=-1)]: Done   7 out of  10 | elapsed:  1.7min remaining:   44.2s


[CV] ....................... , score=0.9808743169398907, total= 1.7min
[CV] ....................... , score=0.9562841530054644, total=  27.7s
[CV] ....................... , score=0.9658469945355191, total=  27.4s
0.9373595137784945
0.04070438429304172


[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:  2.1min finished


In [ ]:
plt.figure(figsize=(10,6))
C=[1,10,100,1000]
plt.plot(C,grid_search)
plt.title('C vs F-1 Score')
plt.xlabel('C')
plt.ylabel('F-1 Score')
plt.show()

In [ ]:
plt.figure(figsize=(10,6))
gamma=[1e-3,1e-4]
plt.plot(gamma,grid_search)
plt.title('Gamma vs F-1 Score')
plt.xlabel('Gamma')
plt.ylabel('F-1 Score')
plt.show()