In [5]:
#Task C:
#Multiclass Logistic Regression with Elastic Net
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
#Importing the dataset
X_train=pd.read_table('X_train.txt',delim_whitespace=True,header=None)
X_test=pd.read_table('X_test.txt',delim_whitespace=True,header=None)
y_train=pd.read_table('y_train.txt',delim_whitespace=True,header=None)
y_test=pd.read_table('y_test.txt',delim_whitespace=True,header=None)

In [7]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [9]:
#Fitting Elastic net classification model
from sklearn.linear_model import SGDClassifier 
alpha_val = 0.1
classifier = SGDClassifier(loss='log', penalty='elasticnet', alpha=alpha_val, l1_ratio=0.7, max_iter=1000) 
classifier.fit(X_train,y_train)

/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(alpha=0.1, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.7, learning_rate='optimal',
       loss='log', max_iter=1000, n_iter=None, n_jobs=1,
       penalty='elasticnet', power_t=0.5, random_state=None, shuffle=True,
       tol=None, verbose=0, warm_start=False)

In [12]:
#Predicting the test set results
y_pred = classifier.predict(X_test)

In [13]:
#Making the confusion matrix,classification report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print('\n')
cr=classification_report(y_test,y_pred)
print(cr)

[[492   2   2   0   0   0]
 [ 35 431   4   0   1   0]
 [145  52 222   0   1   0]
 [  0   7   0 272 212   0]
 [  0   6   0  10 516   0]
 [  0   0   0   0   0 537]]


             precision    recall  f1-score   support

          1       0.73      0.99      0.84       496
          2       0.87      0.92      0.89       471
          3       0.97      0.53      0.69       420
          4       0.96      0.55      0.70       491
          5       0.71      0.97      0.82       532
          6       1.00      1.00      1.00       537

avg / total       0.87      0.84      0.83      2947



In [ ]:
#Applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,scoring='f1_micro',X=X_train,y=y_train,cv=10,n_jobs=-1,verbose=3)
print(accuracies.mean())
print(accuracies.std())

/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
#Applying Grid Search to find the best model andthe best parameters
from sklearn.model_selection import GridSearchCV
parameters=[{'alpha':[1e-4,3e-4,1e-3,3e-3,1e-2,3e-2],'l1_ratio':[0,0.15,0.5,0.7,1]}]
grid_search =GridSearchCV(estimator=classifier,param_grid=parameters,scoring='f1_micro',cv=10,n_jobs=-1,verbose=3)
grid_search=grid_search.fit(X_train,y_train)
best_f1score=grid_search.best_score_
print(best_f1score)
best_parameters =grid_search.best_params_
print(best_parameters)

In [ ]:
from sklearn.model_selection import GridSearchCV
grid_predictions=grid_search.predict(X_test)
print(grid_predictions)

In [ ]:
#Making the confusion matrix,classification report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm1=confusion_matrix(y_test,grid_predictions)
print(cm1)
print('\n')
cr1=classification_report(y_test,grid_predictions)
print(cr1)

In [ ]:
plt.figure(figsize=(10,6))
alpha=[1e-4,3e-4,1e-3,3e-3,1e-2,3e-2]
plt.plot(alpha,grid_search)
plt.title('Alpha vs F-1 Score')
plt.xlabel('Alpha')
plt.ylabel('F-1 Score')
plt.show()

In [ ]:
plt.figure(figsize=(10,6))
l1_ratio=[0,0.15,0.5,0.7,1]
plt.plot(l1_ratio,grid_search)
plt.title('L1_ratio vs F-1 Score')
plt.xlabel('L1_ratio')
plt.ylabel('F-1 Score')
plt.show()