In [1]:
#Task E:
#Random Forest
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Importing the dataset
X_train=pd.read_table('X_train.txt',delim_whitespace=True,header=None)
X_test=pd.read_table('X_test.txt',delim_whitespace=True,header=None)
y_train=pd.read_table('y_train.txt',delim_whitespace=True,header=None)
y_test=pd.read_table('y_test.txt',delim_whitespace=True,header=None)

In [3]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [4]:
#Task-E
#Fitting Random Forest Classifier to the training set
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

/srv/conda/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/srv/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [8]:
#Predicting the test set results
y_pred=classifier.predict(X_test)

In [10]:
#Making the confusion matrix,classification report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print('\n')
cr=classification_report(y_test,y_pred)
print(cr)

[[478  11   7   0   0   0]
 [ 65 392  14   0   0   0]
 [ 19  54 347   0   0   0]
 [  0   0   0 447  44   0]
 [  0   0   0  56 476   0]
 [  0   0   0   1   0 536]]


             precision    recall  f1-score   support

          1       0.85      0.96      0.90       496
          2       0.86      0.83      0.84       471
          3       0.94      0.83      0.88       420
          4       0.89      0.91      0.90       491
          5       0.92      0.89      0.90       532
          6       1.00      1.00      1.00       537

avg / total       0.91      0.91      0.91      2947



In [11]:
#Applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,scoring='f1_micro',X=X_train,y=y_train,cv=10,n_jobs=-1,verbose=3)
print(accuracies.mean())
print(accuracies.std())

[CV]  ................................................................
[CV]  ................................................................
[CV]  ................................................................
[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

[CV] ......................... , score=0.94579945799458, total=  22.2s
[CV]  ................................................................
[CV] ....................... , score=0.9132791327913279, total=  23.0s
[CV]  ................................................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV] ....................... , score=0.8523035230352304, total=  24.5s
[CV] ....................... , score=0.8792401628222524, total=  24.2s


[Parallel(n_jobs=-1)]: Done   3 out of  10 | elapsed:   24.9s remaining:   58.2s


[CV] ....................... , score=0.9198369565217391, total=  23.7s
[CV] ....................... , score=0.9604365620736699, total=  23.4s
[CV] ....................... , score=0.9508196721311475, total=  22.9s


[Parallel(n_jobs=-1)]: Done   7 out of  10 | elapsed:   25.8s remaining:   11.1s


[CV] ....................... , score=0.9103260869565217, total=  24.9s
[CV] ....................... , score=0.9289617486338798, total=   7.1s
[CV] ....................... , score=0.9412568306010929, total=   6.9s


[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:   30.3s finished


0.9202260133561442
0.03188290026615427


In [12]:
#Applying Grid Search to find the best model andthe best parameters
from sklearn.model_selection import GridSearchCV
parameters=[{'n_estimators':[200,500,700],'max_depth':[300,500,600]}]
grid_search =GridSearchCV(estimator=classifier,param_grid=parameters,scoring='f1_micro',cv=10,n_jobs=-1,verbose=3)
grid_search=grid_search.fit(X_train,y_train)
best_f1score=grid_search.best_score_
print(best_f1score)
best_parameters =grid_search.best_params_
print(best_parameters)

Fitting 10 folds for each of 9 candidates, totalling 90 fits
[CV] max_depth=300, n_estimators=200 .................................
[CV] max_depth=300, n_estimators=200 .................................
[CV] max_depth=300, n_estimators=200 .................................
[CV] max_depth=300, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV] max_depth=300, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV] max_depth=300, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV] max_depth=300, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV] max_depth=300, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

[CV]  max_depth=300, n_estimators=200, score=0.8780487804878049, total= 7.4min
[CV] max_depth=300, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=200, score=0.9795081967213115, total= 7.4min
[CV] max_depth=300, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=200, score=0.9363143631436315, total= 7.5min
[CV] max_depth=300, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=200, score=0.9715447154471545, total= 7.5min
[CV] max_depth=300, n_estimators=500 .................................
[CV]  max_depth=300, n_estimators=200, score=0.9252717391304348, total= 7.6min
[CV] max_depth=300, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=200, score=0.8656716417910447, total= 7.6min
[CV] max_depth=300, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=200, score=0.9497282608695652, total= 7.6min
[CV] max_depth=300, n_estimators=500 .................................
[CV]  max_depth=300, n_estimators=200, score=0.9727148703956344, total= 7.6min
[CV] max_depth=300, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=200, score=0.953551912568306, total= 7.4min
[CV] max_depth=300, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=200, score=0.9549180327868853, total= 7.5min
[CV] max_depth=300, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.9322493224932249, total=18.6min
[CV] max_depth=300, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.8794037940379403, total=18.7min
[CV] max_depth=300, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.8697421981004071, total=18.7min
[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.9510869565217391, total=18.8min
[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.9320652173913043, total=19.1min
[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.9728997289972899, total=19.3min


[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed: 27.1min


[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.9781420765027322, total=19.8min
[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.9727148703956344, total=20.0min
[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.9521857923497268, total=20.0min
[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=500, score=0.9590163934426229, total=19.9min
[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=700, score=0.9363143631436315, total=27.0min
[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=700, score=0.8807588075880759, total=27.3min
[CV] max_depth=300, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=700, score=0.8697421981004071, total=27.3min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=700, score=0.9715447154471545, total=27.8min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.9363143631436315, total= 7.9min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=700, score=0.9320652173913043, total=27.5min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=700, score=0.9510869565217391, total=27.5min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.8780487804878049, total= 7.9min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.9715447154471545, total= 8.4min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.9252717391304348, total= 8.3min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.8656716417910447, total= 8.5min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.9497282608695652, total= 8.4min
[CV] max_depth=500, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=700, score=0.9781420765027322, total=28.1min
[CV] max_depth=500, n_estimators=500 .................................
[CV]  max_depth=300, n_estimators=700, score=0.9727148703956344, total=28.2min
[CV] max_depth=500, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.9727148703956344, total= 7.9min
[CV] max_depth=500, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.9795081967213115, total= 7.8min
[CV] max_depth=500, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.953551912568306, total= 7.8min
[CV] max_depth=500, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=200, score=0.9549180327868853, total= 7.9min
[CV] max_depth=500, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=700, score=0.9521857923497268, total=28.2min
[CV] max_depth=500, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=300, n_estimators=700, score=0.9562841530054644, total=28.3min
[CV] max_depth=500, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.9322493224932249, total=20.3min
[CV] max_depth=500, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.8794037940379403, total=20.3min
[CV] max_depth=500, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.9320652173913043, total=20.6min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.8697421981004071, total=20.9min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.9728997289972899, total=21.2min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.9510869565217391, total=20.7min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.9727148703956344, total=21.5min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.9781420765027322, total=21.7min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.9521857923497268, total=21.8min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=500, score=0.9590163934426229, total=22.1min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.9363143631436315, total=28.8min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.8807588075880759, total=29.3min
[CV] max_depth=500, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.8697421981004071, total=29.3min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.9715447154471545, total=29.5min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.9320652173913043, total=29.3min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.9510869565217391, total=29.2min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.8780487804878049, total= 8.7min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.9363143631436315, total= 8.8min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.9715447154471545, total= 9.0min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.8656716417910447, total= 8.7min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.9727148703956344, total=29.1min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.9781420765027322, total=29.4min
[CV] max_depth=600, n_estimators=200 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.9252717391304348, total= 8.6min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.9497282608695652, total= 8.6min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.9727148703956344, total= 7.8min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.9795081967213115, total= 7.6min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.953551912568306, total= 7.3min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=200, score=0.9549180327868853, total= 7.5min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.9521857923497268, total=28.6min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=500, n_estimators=700, score=0.9562841530054644, total=29.0min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.8794037940379403, total=19.2min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.9322493224932249, total=19.5min
[CV] max_depth=600, n_estimators=500 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.8697421981004071, total=19.3min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.9728997289972899, total=19.6min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.9320652173913043, total=20.2min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.9510869565217391, total=20.0min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.9727148703956344, total=19.4min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.9781420765027322, total=19.5min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.9521857923497268, total=18.5min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=500, score=0.9590163934426229, total=18.9min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=700, score=0.9363143631436315, total=25.8min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=700, score=0.8807588075880759, total=26.0min
[CV] max_depth=600, n_estimators=700 .................................


/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV]  max_depth=600, n_estimators=700, score=0.9715447154471545, total=26.5min
[CV]  max_depth=600, n_estimators=700, score=0.8697421981004071, total=26.5min
[CV]  max_depth=600, n_estimators=700, score=0.9320652173913043, total=25.7min
[CV]  max_depth=600, n_estimators=700, score=0.9510869565217391, total=25.5min
[CV]  max_depth=600, n_estimators=700, score=0.9727148703956344, total=21.8min
[CV]  max_depth=600, n_estimators=700, score=0.9781420765027322, total=21.3min
[CV]  max_depth=600, n_estimators=700, score=0.9521857923497268, total=13.7min
[CV]  max_depth=600, n_estimators=700, score=0.9562841530054644, total=13.5min


[Parallel(n_jobs=-1)]: Done  90 out of  90 | elapsed: 210.2min finished
/srv/conda/lib/python3.6/site-packages/sklearn/model_selection/_search.py:740: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


0.9400163220892275
{'max_depth': 300, 'n_estimators': 700}


In [17]:
grid_predictions=grid_search.predict(X_test)
print(grid_predictions)

[5 5 5 ... 2 2 1]


In [18]:
#Making the confusion matrix,classification report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm1=confusion_matrix(y_test,grid_predictions)
print(cm1)
print('\n')
cr1=classification_report(y_test,grid_predictions)
print(cr1)

[[478  11   7   0   0   0]
 [ 35 430   6   0   0   0]
 [ 20  46 354   0   0   0]
 [  0   0   0 438  53   0]
 [  0   0   0  29 503   0]
 [  0   0   0   0   0 537]]


             precision    recall  f1-score   support

          1       0.90      0.96      0.93       496
          2       0.88      0.91      0.90       471
          3       0.96      0.84      0.90       420
          4       0.94      0.89      0.91       491
          5       0.90      0.95      0.92       532
          6       1.00      1.00      1.00       537

avg / total       0.93      0.93      0.93      2947



In [ ]:
plt.figure(figsize=(10,6))
n_estimators=[200,500,700]
plt.plot(n_estimators,grid_search)
plt.title('Tree Depth vs F-1 Score')
plt.xlabel('Tree Depth')
plt.ylabel('F-1 Score')
plt.show()

In [ ]:
plt.figure(figsize=(10,6))
Tree_width=[300,500,600]
plt.plot(Tree_width,grid_search)
plt.title('Number of Trees vs F-1 Score')
plt.xlabel('Number of Trees')
plt.ylabel('F-1 Score')
plt.show()